spring:
  datasource:
    name: miaosha
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/miaosha?characterEncoding=utf-8&useSSL=false
#   使用阿里巴巴的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml

